### ISSUE TITLE
Dockerise application

### ISSUE THREAD

**Issue by wfaithfull** [CodeforLancaster/sitegeist#1]
We need to wrap this application into a dockerfile. In my opinion, this dockerfile should exclude stanford coreNLP server. What we need then is:

- Dockerfile for SiteGeist
- Dockerfile for Stanford CoreNLP

That way, we can run a single Stanford CoreNLP image on our server (which is a very heavy application), and we can potentially run lots of SiteGeist instances all pointing at the same NLP server. Since each SiteGeist application is only concerned with one geofence, if we want to cover multiple areas we need to run many of them.

This limitation is by design - the task of dynamically setting the geofence requires us to have knowledge of all tweets, because we can't know their geographic location in advance. It is a task that would require a lot of Twitter API access and a lot of heavy lifting.

**Comment by benjamenjohnsondev** [comment]
Dockerfile for NLP here: https://github.com/NLPbox/stanford-corenlp-docker

**Comment by wfaithfull** [comment]
Excellent, thought there would be one but that saves me looking around.

**Comment by jon1010hill** [comment]
NLP no longer required

**Comment by wfaithfull** [comment]
Yep, coreNLP has been removed now as of #5 (PR #6). This should be good as a standalone docker image now.

**Comment by jon1010hill** [comment]
I've setup a repo on docker hub that builds an image from master branch.
I'm thinking of setting up a really light http server on the linode that docker hub can ping
every time a new image is built.

**Comment by wfaithfull** [comment]
@jon1010hill sounds sensible. We could even just run an NGINX to delegate to a shell script like [this](https://stackoverflow.com/questions/22891148/nginx-how-to-run-a-shell-script-on-every-request).

**Comment by jon1010hill** [comment]
or circleci

**Comment by jon1010hill** [comment]
I'm making good progress with CircleCI.
Seems to do what we need, should finish it this weekend.
