### ISSUE TITLE
Tweak algorithm to disregard any superfluous words

### ISSUE THREAD

**Issue by neilmorton** [CodeforLancaster/sitegeist#17]
When looking at http://www.codeforlancaster.org.uk at the CfL meet on 30th April 2019, words such as "who" were showing in the sentiment.

Once we have some data, perhaps any superfluous words can be added to a disregard list (which we assume must exist for other words already).

**Comment by ryancallihan** [comment]
I noticed the same thing. I will check that out along with making the "Entities" and "Phrases" a bit better.

**Comment by ryancallihan** [comment]
I made some tweaks. I am going to let it run a bit to see how much better it is working.

**Comment by ryancallihan** [comment]
Ok, I think I got something that works pretty well. I am going to submit a pull request for it. I added a "Words" and "Emojis" option as well.

**Comment by neilmorton** [comment]
Closing issue as group no longer active.
