### ISSUE TITLE
Tweet Summaries

### ISSUE THREAD

**Issue by ryancallihan** [CodeforLancaster/sitegeist#7]
It would be useful to be able to see a summary of tweets throughout the day/week/month/etc. 

Basically, there are a couples ideas:

__Save top terms for the day:__

| text  | count | total_sent | type | date     | avg_sent |
|-------|-------|------------|-------|----------|----------|
| #yeet | 10    | 10.4       | 1     | 20190414 | 1.04     |
|       |       |            |       |          |          |

__Save top tweets:__

Save the highest weighted tweets from the day. This could also be done throughout the day. (Once an hour, for example)

**Comment by wfaithfull** [comment]
So this table will be keyed with a composite of [text, date]

`CREATE TABLE top_terms (subject TEXT, count INTEGER, total_sent REAL, type INTEGER, date DATE, avg_sent REAL, PRIMARY KEY(subject, date))`

**Comment by wfaithfull** [comment]
Also, this is probably best done using a `SELECT INTO` statement, if that's supported by SQLite. Otherwise, there's a whole unnecessary serialisation/deserialisation step into python objects and back. A timed job would only need to run once a day.
